var num = 1;
console.log('var num = 1:' + num);
num = 3;
console.log('num = 3:' + num);
var price = 1.5;
console.log('var price = 1.5:' + price);
var name = 'Dario';
console.log('var name = "Dario":' + name);
var trueValue = true;
console.log('var trueValue = true:' + trueValue);
var nullVar = null;
console.log('var nullVar = null:' + nullVar);
var und;
console.log('var und:' + und);